### ISSUE TITLE
Error in prepare_template when setting up "custom video code"

### ISSUE THREAD

**Issue by radman-rt** [JanaldoChen/Anim-NeRF#11]
Command:
!python -m tools.prepare_template --data_root data/custom --people_ID BAR_APose --model_type smpl --gender neutral --model_path smplx/models/

Result:
  0% 0/256 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/ColabNotebooks/NeRF/Anim-NeRF/tools/prepare_template.py", line 86, in <module>
    distances_chunk = body_mesh.nearest.signed_distance(points_chunk)
  File "/usr/local/lib/python3.7/dist-packages/trimesh/proximity.py", line 307, in signed_distance
    return signed_distance(self._mesh, points)
  File "/usr/local/lib/python3.7/dist-packages/trimesh/proximity.py", line 231, in signed_distance
    closest, distance, triangle_id = closest_point(mesh, points)
  File "/usr/local/lib/python3.7/dist-packages/trimesh/proximity.py", line 138, in closest_point
    candidates = nearby_faces(mesh, points)
  File "/usr/local/lib/python3.7/dist-packages/trimesh/proximity.py", line 43, in nearby_faces
    rtree = mesh.triangles_tree
  File "/usr/local/lib/python3.7/dist-packages/trimesh/caching.py", line 103, in get_cached
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/trimesh/base.py", line 811, in triangles_tree
    tree = triangles.bounds_tree(self.triangles)
  File "/usr/local/lib/python3.7/dist-packages/trimesh/triangles.py", line 338, in bounds_tree
    tree = util.bounds_tree(triangle_bounds)
  File "/usr/local/lib/python3.7/dist-packages/trimesh/util.py", line 1597, in bounds_tree
    import rtree
ModuleNotFoundError: No module named 'rtree'

**Comment by JanaldoChen** [comment]
You can try to pip install rtree.

**Comment by radman-rt** [comment]
Thanx. This worked fine.
