### ISSUE TITLE
ValueError: The provided lr scheduler "<torch.optim.lr_scheduler.LambdaLR object at 0x7ff05e108be0>" is invalid

### ISSUE THREAD

**Issue by SFGHRT** [JanaldoChen/Anim-NeRF#31]

**Comment by SFGHRT** [comment]
Traceback (most recent call last):
  File "/workspace/psen/Anim-NeRF-main/train.py", line 478, in <module>
    trainer.fit(system, data, ckpt_path=cfg.train.ckpt_path if cfg.train.resume else None)
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 683, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 773, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1141, in _run
    self.accelerator.setup(self)
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/accelerators/gpu.py", line 46, in setup
    return super().setup(trainer)
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 93, in setup
    self.setup_optimizers(trainer)
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 351, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 245, in init_optimizers
    return trainer.init_optimizers(model)
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/trainer/optimizers.py", line 44, in init_optimizers
    lr_schedulers = self._configure_schedulers(lr_schedulers, monitor, not pl_module.automatic_optimization)
  File "/usr/local/anaconda3/envs/Animatable/lib/python3.9/site-packages/pytorch_lightning/trainer/optimizers.py", line 192, in _configure_schedulers
    raise ValueError(f'The provided lr scheduler "{scheduler}" is invalid')
ValueError: The provided lr scheduler "<torch.optim.lr_scheduler.LambdaLR object at 0x7ff05e108be0>" is invalid

**Comment by SFGHRT** [comment]
Dear author, can you tell me which part of anim_nerf_test.npz got this? I did not see this file after running the experiment @JanaldoChen
