### ISSUE TITLE
Getting error running inference

### ISSUE THREAD

**Issue by radman-x** [JanaldoChen/Anim-NeRF#4]
Installed all requirements.
Downloaded the pre-trained model and put into /checkpoints from Google Drive.
Downloaded the people-snapshot dataset (male-3-casual), unzipped and put into /data from Google Drive.
Run extract mesh inference as follows
!python extract_mesh.py --ckpt_path checkpoints/male-3-casual/last.ckpt

Got error:

Traceback (most recent call last):
  File "extract_mesh.py", line 103, in <module>
    system = AnimNeRFSystem.load_from_checkpoint(args.ckpt_path).to(device)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/saving.py", line 156, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/saving.py", line 198, in _load_model_state
    model = cls(**_cls_kwargs)
  File "/content/drive/MyDrive/ColabNotebooks/NeRF/Anim-NeRF/train.py", line 125, in __init__
    query_inside=self.hparams.query_inside,
  File "/content/drive/MyDrive/ColabNotebooks/NeRF/Anim-NeRF/models/anim_nerf.py", line 79, in __init__
    self.body_model = create(model_path, model_type, gender=gender)
  File "/content/drive/MyDrive/ColabNotebooks/NeRF/Anim-NeRF/smplx/body_models.py", line 2457, in create
    raise ValueError(f'Unknown model type {model_type}, exiting!')
ValueError: Unknown model type models, exiting!

**Comment by JanaldoChen** [comment]
You need to download the smpl models from https://smpl.is.tue.mpg.de/, and put them in smplx/models.

**Comment by radman-x** [comment]
Still not working:

Traceback (most recent call last):
File "extract_mesh.py", line 103, in
system = AnimNeRFSystem.load_from_checkpoint(args.ckpt_path).to(device)
File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/saving.py", line 156, in load_from_checkpoint
model = cls._load_model_state(checkpoint, strict=strict, kwargs)
File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/saving.py", line 198, in _load_model_state
model = cls(_cls_kwargs)
File "/content/drive/MyDrive/ColabNotebooks/NeRF/Anim-NeRF/train.py", line 125, in init
query_inside=self.hparams.query_inside,
File "/content/drive/MyDrive/ColabNotebooks/NeRF/Anim-NeRF/models/anim_nerf.py", line 79, in init
self.body_model = create(model_path, model_type, gender=gender)
File "/content/drive/MyDrive/ColabNotebooks/NeRF/Anim-NeRF/smplx/body_models.py", line 2447, in create
return SMPL(model_path, **kwargs)
File "/content/drive/MyDrive/ColabNotebooks/NeRF/Anim-NeRF/smplx/body_models.py", line 132, in init
smpl_path)
AssertionError: Path ./smplx/models/smpl/SMPL_MALE.pkl does not exist!

In the link you gave, there are two main download zips for python users: SMPL_python_v1.1.0.zip and SMPL_python_v1.0.0.zip. Both have a models sub-folder containing files like "basicmodel_m_lbs_10_207_0_v1.1.0.pkl" (one for male, female and neutral). None contain anything like "SMPL_MALE.pkl".

**Comment by JanaldoChen** [comment]
You should rename the "basicmodel_m_lbs_10_207_0_v1.1.0.pkl" to "SMPL_MALE.pkl", more details please see https://github.com/vchoutas/smplx.

**Comment by radman-x** [comment]
Thanx. That worked fine, can now run inference. For the record, I used basicmodel_m_lbs_10_207_0_v1.1.0.pkl (renamed to SMPL_MALE.pkl) and also tested basicmodel_m_lbs_10_207_0_v1.0.0.pkl -- both seemed to work equally well.

Thanx again for your great work!
